language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mherzner/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mherzner/react-test npm test

after_success:
  - docker build -t mherzner/multi-client ./client
  - docker build -t mherzner/multi-nginx ./nginx
  - docker build -t mherzner/multi-server ./server
  - docker build -t mherzner/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push mherzner/multi-client
  - docker push mherzner/multi-nginx
  - docker push mherzner/multi-server
  - docker push mherzner/multi-worker